steps:
# build and tag with short SHA
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/hello:$SHORT_SHA',
            '-t', 'gcr.io/$PROJECT_ID/hello:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/golang:alpine3.12',
            'application/go'
        ]

# Push image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hello:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hello:latest']

# Deploy new image to GKE (will override image name:tag in k8s manifest)
# - name: 'gcr.io/cloud-builders/gke-deploy'
#   args:
#   - run
#   - --filename=kubernetes/hello.yaml
#   - --image=gcr.io/$PROJECT_ID/hello:$SHORT_SHA
#   - --location=us-east1
#   - --cluster=hello-gke